[package]
name = "dutty"
version = "0.1.0"
edition = "2018"
description = """
Dummy teletype utility
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
'atty' = "0.2.14"
'clap' = "2.33.3"
